include:
  - template: Terraform/Base.gitlab-ci.yml

stages:
  - init
  - validate
  - build
  - test
  - deploy

init:
  extends: .init

validate:
  extends: .validate

build:
  stage: .build
  script: 
    - echo "Compiling the code."

test:
  stage: .test
  script: "Running unit tests... This will take about 60 seconds."

deploy: 
  stage: .deploy
  environment: production
  script: echo "Deploying applicacion."  

