stages:
  - build
  - deploy

build website:
  image: node:lts-alpine3.17
  stage: build
  script:
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - build  

deploy to s3:
  stage: deploy
  image: 
    name: amazon/aws-cli:2.11.3
    entrypoint: ['']
  script:
    - aws --version
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete
