include:
  - template: Terraform/Base.gitlab-ci.yml

stages:
  - init
  - validate
  - build
  - deploy

init:
  extends: .init

validate:
  extends: .validate

build:
  stage: .build
  script: 
    - echo "Compiling the code."

deploy: 
  stage: .deploy
  environment: production
  script: echo "Deploying applicacion."  

