
stages:         
  - build
  - test
  - deploy

build:      
  stage: build
  script:
    - echo "Compiling the code..."

test:  
  stage: test    
  script:
    - echo "Running unit tests..."

deploy:    
  stage: deploy  
  script:
    - echo "Deploying application..."
  
