stages:
  - build
  - deploy

build artifact:
  stage: build
  image: node:latest
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - build
    when: always
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always

deploy to s3:
  stage: deploy
  image: 
    name: amazon/aws-cli:2.11.3
    entrypoint: ['']
  script:
    - aws --version
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete
